import Head from "next/head"
import { Roboto } from 'next/font/google'
import Header from "@/components/Header"


type layout ={ 
  children: JSX.Element
}
const inter = Roboto({ weight: "400", subsets: ["latin"] })

const Layout = ({children}: layout) => {

  return (
    <div className={inter.className}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <Header />
        <main >
          <div className="container">
            {children}
          </div>
        </main>
      </div>
    </div>
  )

}

export default Layout